///////////////////////////////////////////////////////////
//  GeneratorType.cs
//  Implementation of the Enumeration GeneratorType
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CommonLibrary
{

    public enum GeneratorType : int
    {

        WIND_STATIC,
        WIND_DYNAMIC,
        SOLAR,
        MICROHYDRO

    }
}