///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace CommonLibrary
{
    [DataContract]
    public class Group : IdentifiedObject
    {

        private string siteID;

        public Group()
        {

        }

        [DataMember]
        public string SiteID
        {
            get
            {
                return siteID;
            }

            set
            {
                siteID = value;
            }
        }

        [DataMember]
        public void EstimateMeasurment()
        {

        }
    }//end Group
}