///////////////////////////////////////////////////////////
//  IdentifiedObject.cs
//  Implementation of the Class IdentifiedObject
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;
using System.ComponentModel;

namespace CommonLibrary
{
    [DataContract]
    public abstract class IdentifiedObject
    {

        private string mrID;
        private string name;

        public IdentifiedObject()
        {

        }

        [DataMember]
        public string MRID
        {
            get
            {
                return mrID;
            }
            set
            {
                mrID = value;
                RaisePropertyChanged("mrID");
            }
        }

        [DataMember]
        public string Name
        {
            get
            {
                return name;
            }

            set
            {
                name = value;
                RaisePropertyChanged("name");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propName));
            }
        }
    }//end IdentifiedObject
}