///////////////////////////////////////////////////////////
//  IdentifiedObject.cs
//  Implementation of the Class IdentifiedObject
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CommonLibrary
{
    public abstract class IdentifiedObject
    {

        private string mrID;
        private string name;

        public IdentifiedObject()
        {

        }

        public string MRID
        {
            get
            {
                return mrID;
            }
            set
            {
                mrID = value;
            }
        }

        public string Name
        {
            get
            {
                return name;
            }

            set
            {
                name = value;
            }
        }
    }//end IdentifiedObject
}