///////////////////////////////////////////////////////////
//  LKResService.cs
//  Implementation of the Class LKResService
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using CommonLibrary.Interfaces;
using System.Runtime.Serialization;

namespace CommonLibrary
{
    [DataContract]
    public class LKResService
    {
        private string username;
        private ILKRes client;
        private string sessionID;
        private List<Site> sites;
        private List<Group> gropus;
        private List<Generator> generators;

        public LKResService(string username, ILKRes channel, string sessionID)
        {
            this.username = username;
            this.client = channel;
            this.sites = new List<Site>();
            this.gropus = new List<Group>();
            this.generators = new List<Generator>();
            this.sessionID = sessionID;
        }

        [DataMember]
        public string Username
        {
            get
            {
                return username;
            }
            set
            {
                username = value;
            }
        }

        [DataMember]
        public List<Site> Sites
        {
            get
            {
                return sites;
            }

            set
            {
                sites = value;
            }
        }

        [IgnoreDataMember]
        public ILKRes Client
        {
            get
            {
                return client;
            }

            set
            {
                client = value;
            }
        }

        [DataMember]
        public List<Group> Gropus
        {
            get
            {
                return gropus;
            }

            set
            {
                gropus = value;
            }
        }

        [DataMember]
        public List<Generator> Generators
        {
            get
            {
                return generators;
            }

            set
            {
                generators = value;
            }
        }

        [IgnoreDataMember]
        public string SessionID
        {
            get
            {
                return sessionID;
            }

            set
            {
                sessionID = value;
            }
        }
    }//end LKResService
}