///////////////////////////////////////////////////////////
//  SetPoint.cs
//  Implementation of the Class SetPoint
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CommonLibrary
{
    public class Point
    {

        private string generatorID;
        private double power;

        public double Power
        {
            get
            {
                return power;
            }
            set
            {
                power = value;
            }
        }

        public string GeneratorID
        {
            get
            {
                return generatorID;
            }
            set
            {
                generatorID = value;
            }
        }

    }//end SetPoint
}