///////////////////////////////////////////////////////////
//  Site.cs
//  Implementation of the Class Site
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace CommonLibrary
{
    [DataContract]
    public class Site : IdentifiedObject
    {
        public Site()
        {

        }
    }//end Site
}