///////////////////////////////////////////////////////////
//  UpdateInfo.cs
//  Implementation of the Class UpdateInfo
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace CommonLibrary
{
    [DataContract]
    public class UpdateInfo
    {
        private UpdateType updateType;
        private Generator generator;
        private Group group;
        private Site site;

        [DataMember]
        public UpdateType UpdateType
        {
            get
            {
                return updateType;
            }

            set
            {
                updateType = value;
            }
        }

        [DataMember]
        public Generator Generator
        {
            get
            {
                return generator;
            }

            set
            {
                generator = value;
            }
        }

        [DataMember]
        public Group Group
        {
            get
            {
                return group;
            }

            set
            {
                group = value;
            }
        }

        [DataMember]
        public Site Site
        {
            get
            {
                return site;
            }

            set
            {
                site = value;
            }
        }
    }//end UpdateInfo
}