///////////////////////////////////////////////////////////
//  UpdateInfo.cs
//  Implementation of the Class UpdateInfo
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace CommonLibrary
{
    [DataContract]
    public class UpdateInfo
    {
        private UpdateType updateType;
        private List<Generator> generators;
        private List<Group> groups;
        private List<Site> sites;

        public UpdateInfo()
        {
            updateType = UpdateType.ADD;
            generators = new List<Generator>();
            groups = new List<Group>();
            sites = new List<Site>();
        }

        [DataMember]
        public UpdateType UpdateType
        {
            get
            {
                return updateType;
            }

            set
            {
                updateType = value;
            }
        }

        [DataMember]
        public List<Generator> Generators
        {
            get
            {
                return generators;
            }

            set
            {
                generators = value;
            }
        }

        [DataMember]
        public List<Group> Groups
        {
            get
            {
                return groups;
            }

            set
            {
                groups = value;
            }
        }

        [DataMember]
        public List<Site> Sites
        {
            get
            {
                return sites;
            }

            set
            {
                sites = value;
            }
        }
    }//end UpdateInfo
}