///////////////////////////////////////////////////////////
//  UpdateInfo.cs
//  Implementation of the Class UpdateInfo
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CommonLibrary
{
    public class UpdateInfo
    {

        private UpdateType updateType;
        private Generator generator;

        public UpdateType UpdateType
        {
            get
            {
                return updateType;
            }

            set
            {
                updateType = value;
            }
        }

        public Generator Generator
        {
            get
            {
                return generator;
            }

            set
            {
                generator = value;
            }
        }
    }//end UpdateInfo
}