///////////////////////////////////////////////////////////
//  UpdateType.cs
//  Implementation of the Enumeration UpdateType
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace CommonLibrary
{
    public enum UpdateType : int
    {

        UPDATE = 1,
        ADD,
        REMOVE

    }//end UpdateType
}