///////////////////////////////////////////////////////////
//  WorkingMode.cs
//  Implementation of the Enumeration WorkingMode
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum WorkingMode : int {

	LOCAL,
	REMOTE

}//end WorkingMode