///////////////////////////////////////////////////////////
//  IKSClient.cs
//  Implementation of the Interface IKSClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.26
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace InterfaceForDuplex {
	public interface IKSClient  {

		/// 
		/// <param name="update"></param>
		/// <param name="username"></param>
		void Update(UpdateInfo update, string username);
	}//end IKSClient

}//end namespace InterfaceForDuplex