///////////////////////////////////////////////////////////
//  IKSForClient.cs
//  Implementation of the Interface IKSForClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace CommonLibrary.Interfaces
{
    [ServiceContract]
    public interface IKSForClient
    {
        [OperationContract]
        List<LKResService> GetAllSystem();
        [OperationContract]
        void IssueCommand(double requiredAP);
        [OperationContract]
        SortedDictionary<DateTime, double> GetLoadForecast();

        [OperationContract]
        SortedDictionary<DateTime, double> GetProductionHistory(double days);
    }
}