///////////////////////////////////////////////////////////
//  IKSForClient.cs
//  Implementation of the Interface IKSForClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace InterfaceForDuplex {
	public interface IKSForClient  {

		List<LKResService> GetAllSystem();

		/// 
		/// <param name="username"></param>
		/// <param name="requiredAP"></param>
		void IssueCommand(string username, double requiredAP);
	}//end IKSForClient

}//end namespace InterfaceForDuplex