///////////////////////////////////////////////////////////
//  IKSRes.cs
//  Implementation of the Interface IKSRes
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using CommonLibrary.Exceptions;

namespace CommonLibrary.Interfaces
{
    public interface IKSRes
    {
        [OperationContract]
        [FaultContract(typeof(IdentificationExeption))]
        void Login(string username, string password);
        
        [OperationContract]
        [FaultContract(typeof(IdentificationExeption))]
        void Registration(string username, string password);
        
        [OperationContract]
        void SendMeasurement(Dictionary<string, double> measurments);
        
        [OperationContract]
        void Update(UpdateInfo update);
    }
}