///////////////////////////////////////////////////////////
//  IKSRes.cs
//  Implementation of the Interface IKSRes
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IKSRes  {

	/// 
	/// <param name="username"></param>
	/// <param name="password"></param>
	void Login(string username, string password);

	/// 
	/// <param name="username"></param>
	/// <param name="password"></param>
	void Registration(string username, string password);

	/// 
	/// <param name="measurments"></param>
	void SendMeasurement(Dictionary<string, double> measurments);

	/// 
	/// <param name="update"></param>
	void Update(UpdateInfo update);
}//end IKSRes