///////////////////////////////////////////////////////////
//  IKSRes.cs
//  Implementation of the Interface IKSRes
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using CommonLibrary.Exceptions;

namespace CommonLibrary.Interfaces
{
    [ServiceContract]
    public interface IKSRes
    {
        /// 
        /// <param name="username"></param>
        /// <param name="password"></param>
        [OperationContract]
        [FaultContract(typeof(IdentificationExeption))]
        void Login(string username, string password);

        /// 
        /// <param name="username"></param>
        /// <param name="password"></param>
        [OperationContract]
        [FaultContract(typeof(IdentificationExeption))]
        void Registration(string username, string password);

        /// 
        /// <param name="measurments"></param>
        [OperationContract]
        void SendMeasurement(Dictionary<string, double> measurments);

        /// 
        /// <param name="update"></param>
        [OperationContract]
        void Update(UpdateInfo update);
    }
}