///////////////////////////////////////////////////////////
//  ILKClient.cs
//  Implementation of the Interface ILKClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CommonLibrary.Interfaces
{
	public interface ILKClient  {

		/// 
		/// <param name="update"></param>
		void Update(UpdateInfo update);
	}//end ILKClient

}//end namespace InterfaceForDuplex