///////////////////////////////////////////////////////////
//  ILKForClient.cs
//  Implementation of the Interface ILKForClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;



namespace CommonLibrary.Interfaces
{
    [ServiceContract(CallbackContract = typeof(ILKClient))]
    public interface ILKForClient  {

        [OperationContract]
		UpdateInfo GetMySystem();

        [OperationContract]
        /// <param name="update"></param>
        void Update(UpdateInfo update);

        [OperationContract]
		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		void Login(string username, string password);

        [OperationContract]
		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		void Registration(string username, string password);

    }//end ILKForClient

}//end namespace InterfaceForDuplex