///////////////////////////////////////////////////////////
//  ILKForClient.cs
//  Implementation of the Interface ILKForClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;



namespace CommonLibrary.Interfaces
{
    // [ServiceContract(CallbackContract = typeof(ILKClient))]
    [ServiceContract]
    public interface ILKForClient
    {
        [OperationContract]
        UpdateInfo GetMySystem();

        [OperationContract]
        void Update(UpdateInfo update);

        [OperationContract]
        void Login(string username, string password);

        [OperationContract]
        void Registration(string username, string password);

        [OperationContract]
        List<KeyValuePair<DateTime, double>> GetMeasurements(string mRID);
    }
}