///////////////////////////////////////////////////////////
//  ILKForClient.cs
//  Implementation of the Interface ILKForClient
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.27
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CommonLibrary.Interfaces
{
	public interface ILKForClient  {

		List<Site> GetMySystem();

		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		void Login(string username, string password);

		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		void Registration(string username, string password);
	}//end ILKForClient

}//end namespace InterfaceForDuplex