///////////////////////////////////////////////////////////
//  ILKRes.cs
//  Implementation of the Interface ILKRes
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CommonLibrary
{
    public interface ILKRes
    {

        string Ping();

        /// 
        /// <param name="setPoints"></param>
        void SendSetPoint(List<SetPoint> setPoints);
    }//end ILKRes
}