///////////////////////////////////////////////////////////
//  ILKRes.cs
//  Implementation of the Interface ILKRes
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

namespace CommonLibrary.Interfaces
{
    [ServiceContract]
    public interface ILKRes
    {
        [OperationContract]
        string Ping();

        [OperationContract]
        /// 
        /// <param name="setPoints"></param>
        void SendSetPoint(List<Point> setPoints);

        [OperationContract]
        void SendBasePoint(Dictionary<int, List<Point>> basePoints);
    }//end ILKRes
}