///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Group : IdentifiedObject {

	private List<Generator> generators;

	public Group(){

	}

    public List<Generator> Generators
    {
        get
        {
            return generators;
        }

        set
        {
            generators = value;
        }
    }

    public void EstimateMeasurment(){

	}

}//end Group