///////////////////////////////////////////////////////////
//  LKResService.cs
//  Implementation of the Class LKResService
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LKResService {

	private string username;
	private ILKRes client;
	private List<Site> sites;

	public LKResService(){

	}

	public string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

    public List<Site> Sites
    {
        get
        {
            return sites;
        }

        set
        {
            sites = value;
        }
    }

    public ILKRes Client
    {
        get
        {
            return client;
        }

        set
        {
            client = value;
        }
    }
}//end LKResService