///////////////////////////////////////////////////////////
//  Site.cs
//  Implementation of the Class Site
//  Generated by Enterprise Architect
//  Created on:      27-dec-2016 11.40.04
//  Original author: Gogic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Site : IdentifiedObject {

	private List<Group> groups;

	public Site(){

	}

    public List<Group> Groups
    {
        get
        {
            return groups;
        }

        set
        {
            groups = value;
        }
    }
}//end Site